build:
  version: "3.0"

accounts:
  message: "Welcome to SWL Bank accounts related local APIs "
  contactDetails:
    name: "Amaal Grega - Developer"
    email: "amaal@swlbank.com"
  onCallSupport:
    - (452) 456-2176
    - (546) 764-8934