build:
  version: "3.0"

loans:
  message: "Welcome to AWL Bank accounts related local APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "john@swlbank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345